[package]
name = "chaincash_cli"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"

[dependencies]
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing = { workspace = true }
clap = { workspace = true, features = ["derive"] }
listenfd = { workspace = true }
tokio = { workspace = true, features = ["full"] }
anyhow = { workspace = true }
chaincash_app = { path = "../chaincash_app" }
