[package]
name = "chaincash_cli"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"

[dependencies]
tracing-subscriber = { workspace = true }
tracing = { workspace = true }
clap = { workspace = true }
listenfd = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
chaincash_app = { workspace = true }
