[workspace]
members = ["crates/*"]

[workspace.dependencies]
serde_json = "1.0.108"
thiserror = "1.0.44"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1.37"
