[workspace]

members = ["crates/*"]

[workspace.dependencies]
thiserror = "1.0.44"
listenfd = "1.0.1"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
chaincash_store = { path = "./crates/chaincash_store" }
anyhow = "1.0.75"
tracing = "0.1.37"
