targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "aarch64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "aarch64-apple-darwin" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
]

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
# temporary, new versions of these crates need to be published
allow-git = [
  "https://github.com/ergoplatform/sigma-rust.git",
  "https://github.com/ergoplatform/ergo-node-interface-rust.git"
]

[licenses]
default = "allow"
