[package]
name = "chaincash_offchain"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"

[dependencies]
once_cell = "1.18.0"
ergo_lib = { git = "https://github.com/ergoplatform/sigma-rust.git", branch = "master", package = "ergo-lib", features = ["compiler"] }
