[package]
name = "chaincash_store"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
diesel = { version = "2.1.3", features = ["sqlite", "r2d2"] }
diesel_migrations = "2.1.0"
thiserror = { workspace = true }
serde = { workspace = true }
