[package]
name = "chaincash_store"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"

[dependencies]

diesel = { workspace = true, features = ["sqlite", "r2d2"] }
diesel_migrations = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
