[package]
name = "chaincash_app"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"

[dependencies]
chaincash_server = { workspace = true }
chaincash_store = { workspace = true }
thiserror = { workspace = true }
listenfd = { workspace = true }
config = { workspace = true }
serde = { workspace = true }
