[server]
url = "127.0.0.1"
port = 8080

[node]
url = "http://localhost:9052"
# hello is the default for nodes
# in prod this should be set with CHAINCASH_NODE.API_KEY env var
api_key = "hello"

[store]
url = "chaincash.sqlite"

[acceptance]
# path to predicate configuration files
# if ANY of these evaluate to true a note will be accepted
predicates = ["config/predicates/example.toml"]
