[package]
name = "chaincash_server"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"

[dependencies]
axum = "0.6.20"
tower = "0.4.13"
hyper = { version = "0.14.27", features = ["full"] }
tracing = "0.1.37"
thiserror = "1.0.44"
chaincash_store = { path = "../chaincash_store" }
