[package]
name = "chaincash_predicate"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
toml = "0.8.6"
serde = { workspace = true }
thiserror = { workspace = true }
