[package]
name = "chaincash_predicate"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"

[dependencies]
serde = { workspace = true, features = ["derive"] }
toml = { workspace = true }
thiserror = { workspace = true }
